image: jelaniwoods/appdev2021-omnicalc-2@sha256:dce4fc6962f901340d90809366d7f25b785eb6f487a4016a71e4c7de26d5bc9e

tasks:
  - command: bundle install
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - wingrunr21.vscode-ruby
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
